---
- hosts: localhost
  connection: local
  become: yes
  tasks:

   - name: Update
     command: sudo apt-get update

   - name: install docker
     apt: 
      name: docker.io
      state: latest

   - name: install docker-compose
     apt: 
      name: docker-compose
      state: latest

   - name: install git
     apt: 
      name: git
      state: latest

   - name: install phyton
     apt: 
      name: python-pip
      state: latest

   - pip:
      name: docker-py
      state: latest

   - name: install java
     apt: 
      name: default-jre
      state: latest

   - name: install maven
     apt: 
      name: maven
      state: latest

   - name: install gdebi
     apt: 
      name: gdebi
      state: latest

   - name: install nodejs
     apt: 
      name: nodejs-legacy
      state: latest

   - name: install mysql
     apt: 
      name: mysql-server
      state: latest
   
   - name: install mysqlworkbench
     apt: 
      name: mysql-workbench
      state: latest

   - name: install MongoDB
     command: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
     command: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
     command: sudo apt-get update
     command: sudo apt-get install -y mongodb

   - name: install rocketchat-desktop
     command: sudo snap install rocketchat-desktop

   - name: install jenkins docker image
     docker_container:
        name: jenkins
        image: jenkins/jenkins
        ports:
          - "8080:8080"
        volumes:
          - ~/opt/jenkins_home:/var/jenkins_home

   - name: install sonarqube docker image
     docker_container:
        name: sonarqube
        image: sonarqube
        ports:
          - "19000:9000"

   - name: install nexus docker image
     docker_container:
        name: nexus
        image: sonatype/nexus
        ports:
          - "8081:8081"

   - name: install gitlab docker image
     docker_container:
        name: gitlab
        image: gitlab/gitlab-ce
        ports:
          - "80:80"
          - "443:443"
          - "22:22"
        volumes:
          - ~/opt/gitlab/etc:/etc/gitlab
          - ~/opt/gitlab/log:/var/log/gitlab
          - ~/opt/gitlab/opt:/var/opt/gitlab

   - name: install eclipse
     command: wget http://artfiles.org/eclipse.org//oomph/epp/oxygen/R/eclipse-inst-linux64.tar.gz

   - name: install aws-cli
     apt: 
      name: awscli
      state: latest

   - name: install vagrant
     apt: 
      name: vagrant
      state: latest

   - name: install virtual box
     apt: 
      name: virtualbox
      state: latest      

   - name: get the Ansible AWX
     command: mkdir awx
     command: cd awx
     command: git clone https://github.com/ansible/awx.git
     command: cd awx/installer/

   - name: change the default user of AWX
     lineinfile:
      path: ./inventory
      regexp: '*default_admin_user=*'
      line: 'default_admin_user=ansibleawx'

   - name: change the default pass of AWX
     lineinfile:
      path: ./inventory
      regexp: '*default_admin_password=*'
      line: 'default_admin_password=ansibleawx@123#'

   - name: install Ansible AWX
     command: ansible-playbook install.yml

   - name: install Visual Studi0 Code
     command: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
     command: sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
     command: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
     command: sudo apt-get install code # or code-insiders

   - name: install Atom
     command: sudo add-apt-repository ppa:webupd8team/atom
     command: sudo apt-get install atom

   - name: install spotify
     command: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
     command: echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
     command: sudo apt-get update
     command: sudo apt-get install spotify-client

   - name: Update
     command: sudo apt-get update

   - name: upgrade
     command: sudo apt-get upgrade
